### ISSUE TITLE
Dont deploy

### ISSUE THREAD

**Issue by avenda** [klokie/bitbucket-post-hook-deployment#1]
I get the follow error when bitbucket make a post hook:

[Sat Aug 23 00:39:15 2014] [error] [client 131.103.20.165] PHP Notice:  Undefined property: Deploy::$_data in /home/user/web/xxxx.com/public_html/folder/Deploy/Deploy.php on line 126
[Sat Aug 23 00:39:15 2014] [error] [client 131.103.20.165] PHP Stack trace:
[Sat Aug 23 00:39:15 2014] [error] [client 131.103.20.165] PHP   1. {main}() /home/user/web/xxxx.com/public_html/folder/git-hook.php:0
[Sat Aug 23 00:39:15 2014] [error] [client 131.103.20.165] PHP   2. Deploy->execute() /home/user/web/xxxx.com/public_html/folder/git-hook.php:78

**Comment by klokie** [comment]
Hi @avenda, that should only happen if you have declared a post_deploy callback and the POST data is empty. But it should be handled now.
