### ISSUE TITLE
Password string

### ISSUE THREAD

**Issue by avenda** [klokie/bitbucket-post-hook-deployment#2]
I use the config.ini and i put a password with the ! char, like this: my_password!

and i get the follow error:

[Fri Aug 22 23:58:09 2014] [error] [client 131.103.20.165] PHP Warning:  syntax error, unexpected '!' in ./config.ini on line 3\n in /home/user/web/xxxx.com/public_html/folder/git-hook.php on line 20
[Fri Aug 22 23:58:09 2014] [error] [client 131.103.20.165] PHP Stack trace:
[Fri Aug 22 23:58:09 2014] [error] [client 131.103.20.165] PHP   1. {main}() /home/user/web/xxxx.com/public_html/folder/git-hook.php:0
[Fri Aug 22 23:58:09 2014] [error] [client 131.103.20.165] PHP   2. parse_ini_file() /home/user/web/xxxx.com/public_html/folder/git-hook.php:20
[Fri Aug 22 23:58:09 2014] [error] [client 131.103.20.165] PHP Warning:  array_merge(): Argument #2 is not an array in /home/user/web/xxxx.com/public_html/folder/git-hook.php on line 20

**Comment by klokie** [comment]
Hi @avenda, sorry about the delay in replying.
Non-alphanumeric strings in .ini files need to be double-quoted. Please see [this related post](http://stackoverflow.com/questions/6684800/syntax-error-using-parse-ini-file-when-files-values-contain-exclamation-poin?answertab=votes#tab-top).
